-   id: linky-note
    name: Generate Backlink Section in Markdown files
    description: This hook will lint Markdown files and generate a backlink Section
    entry: linky-note apply
    language: python
    types: [markdown]
    pass_filenames: false
